config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  resources :menu_products
  resources :menus
  resources :home_pages
  resources :states
  resources :requests
  resources :products 
  resources :categories

  root "home_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: %i[ show edit update destroy ]

  # GET /progresses or /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1 or /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses or /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to progress_url(@progress), notice: "Progress was successfully created." }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1 or /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to progress_url(@progress), notice: "Progress was successfully updated." }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1 or /progresses/1.json
  def destroy
    @progress.destroy

    respond_to do |format|
      format.html { redirect_to progresses_url, notice: "Progress was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def progress_params
      params.require(:progress).permit(:name)
    end
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/_form.html.erb
<%= form_with(model: progress, local: true) do |form| %>
  <% if progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
      <% progress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name , class:"form-control", placeholder:"Nome"%>
  </div>

  <div class="actions">
    <%= form.submit ("Atualizar status"), class:"btn btn-light" %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<br>
<div class="nav justify-content-center">
    <h1>Editando status</h1>
</div>

<%= render 'form', progress: @progress %>

<%= link_to 'Show', @progress, class:"btn btn-light" %> |
<%= link_to 'Back', progresses_path, class:"btn btn-light" %>

app/views/progresses/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="nav justify-content-center">  
  <h1>Status</h1>
</div>

<div class="nav justify-content-center"> 
  <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <tbody>
      <% @progresses.each do |progress| %>
        <tr>
          <td><%= progress.name %></td>
          <td><%= link_to 'Visualizar', progress %></td>
          <td><%= link_to 'Editar', edit_progress_path(progress) %></td>
          <td><%= link_to 'Excluir', progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="nav justify-content-center">
  <%= link_to 'Novo Status', new_progress_path, class:"btn btn-light"%>
</div>

app/views/progresses/new.html.erb
<br>
<div class="nav justify-content-center">
    <h1>Novo status</h1>
</div>

<%= render 'form', progress: @progress, class:"btn btn-light" %>

<%= link_to 'Back', progresses_path, class:"btn btn-light" %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="nav justify-content-center">
 <h1>Status</h1>
</div>

<form>
  <div class="mb-3">  
    <strong>Nome: </strong>
    <%= text_field_tag nil, @progress.name, class:"form-control", disabled: true%>
  </div>
</form>

<%= link_to 'Edit', edit_progress_path(@progress), class:"btn btn-light" %> |
<%= link_to 'Back', progresses_path, class:"btn btn-light" %>