config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  resources :menu_products
  resources :menus
  resources :home_pages
  resources :states
  resources :requests
  resources :products 
  resources :categories

  root "home_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord

    belongs_to :product
    belongs_to :progress
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]
  before_action :set_product_options, only: [ :new, :create, :update, :edit]
  before_action :set_progress_options, only: [ :new, :create, :update, :edit]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)
    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Pedido realizado com sucesso!" }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
    
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Pedido atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Pedido excluído com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    
    def set_product_options
      @product_options = Product.all.pluck(:description, :id)
    end
    
    def set_progress_options
      @progress_options = Progress.all.pluck(:name, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params

      params.require(:request).permit(:requesting_user, :quantity, :product_id, :progress_id)
    end
  end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     
    <div class="mb-3">
      <%= form.label :requesting_user %>
      <%= form.text_field :requesting_user, class:"form-control", placeholder:"Seu nome"%>
    </div>

    <div class="form-group">
        <%= form.label :product %>
        <%= form.select("product_id", @product_options, {include_blank: "selecione..."}, class:"form-control") %>
    </div>
  
    <div class="mb-3">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class:"form-control"%>
    </div>
 
    <div class="form-group">
        <%= form.label :progress %>
        <%= form.select("progress_id", @progress_options, {include_blank: "selecione..."}, class:"form-control") %>
    </div>

    <br>
 
    <div class="actions">
      <%= form.submit ("Concluir pedido"), class:"btn btn-light" %>
    </div>
   
  
<% end %>

app/views/requests/edit.html.erb
<br>
<div class="nav justify-content-center">
    <h1>Editar Pedido</h1>
</div>

<%= render 'form', request: @request %>
<%= link_to 'Back', requests_path, class:"btn btn-light" %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class="nav justify-content-center">
  <h1>Pedidos</h1>
  </div>

<div class="nav justify-content-center">  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Status</th>
        <th>Valor</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @requests.each do |request| %>
        <tr>
          <td><%= request.requesting_user %></td>
          <td><%= request.progress.name %></td>
          <td><%= request.quantity * request.product.preco %></td>
          <td><%= link_to 'Visualizar', request %></td>
          <td><%= link_to 'Editar', edit_request_path(request) %></td>
          <td><%= link_to 'Excluir', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="nav justify-content-center">
  <%= link_to 'Novo pedido', new_request_path, class:"btn btn-light"%>
</div>

app/views/requests/new.html.erb
<br>
<div class="nav justify-content-center">
    <h1>Novo pedido</h1> 
</div>  

<br>

<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="nav justify-content-center">
    <h1>Pedido</h1>
</div>

<form> 
    <div class="mb-3"> 
      <strong>Cliente:</strong>
      <%= text_field_tag nil, @request.requesting_user, class:"form-control", disabled: true%>
    </div>

   <div class="mb-3"> 
      <strong>Produto(s):</strong>
      <%= text_field_tag nil, @request.product.description, class:"form-control", disabled: true%>
    </div>
  
    <div class="mb-3"> 
      <strong>Quantidade:</strong>
      <%= text_field_tag nil, @request.quantity, class:"form-control", disabled: true%>
    </div>
 
    <div class="mb-3"> 
      <strong>Preço:</strong>
      <%= text_field_tag nil, @request.quantity * @request.product.preco, class:"form-control", disabled: true%>
    </div>
</form>

<%= link_to 'Voltar', requests_path, class:"btn btn-light"%> |
<%= link_to 'Página inicial', home_pages_path, class:"btn btn-light"%>