config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  resources :menu_products
  resources :menus
  resources :home_pages
  resources :states
  resources :requests
  resources :products 
  resources :categories

  root "home_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home_page.rb
class HomePage < ApplicationRecord
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_action :set_home_page, only: %i[ show edit update destroy ]

  # GET /home_pages or /home_pages.json
  def index
    @home_pages = HomePage.all
  end

  # GET /home_pages/1 or /home_pages/1.json
  def show
  end

  # GET /home_pages/new
  def new
    @home_page = HomePage.new
  end

  # GET /home_pages/1/edit
  def edit
  end

  # POST /home_pages or /home_pages.json
  def create
    @home_page = HomePage.new(home_page_params)

    respond_to do |format|
      if @home_page.save
        format.html { redirect_to home_page_url(@home_page), notice: "Home page was successfully created." }
        format.json { render :show, status: :created, location: @home_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home_pages/1 or /home_pages/1.json
  def update
    respond_to do |format|
      if @home_page.update(home_page_params)
        format.html { redirect_to home_page_url(@home_page), notice: "Home page was successfully updated." }
        format.json { render :show, status: :ok, location: @home_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_pages/1 or /home_pages/1.json
  def destroy
    @home_page.destroy

    respond_to do |format|
      format.html { redirect_to home_pages_url, notice: "Home page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_page
      @home_page = HomePage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_page_params
      params.require(:home_page).permit(:apresentacao)
    end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/_form.html.erb
<%= form_with(model: home_page, local: true) do |form| %>
  <% if home_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home_page.errors.count, "error") %> prohibited this home_page from being saved:</h2>

      <ul>
      <% home_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :apresentacao %>
    <%= form.text_field :apresentacao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home_pages/edit.html.erb
<h1>Editing Home Page</h1>

<%= render 'form', home_page: @home_page %>

<%= link_to 'Show', @home_page %> |
<%= link_to 'Back', home_pages_path %>

app/views/home_pages/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="nav justify-content-center">  
    <h1>Seja bem vindo!</h1>
  </div>
    
  <br>

  <div class="nav justify-content-center">
    <h2><strong> Lanchonete </strong><h2>
  </div>
  
  <div class="nav justify-content-center">
    <figure class="figure">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrBHeamZyNioLeyEwXFEGVWqvWUH-OYUYAhg&usqp=CAU" class="figure-img img-fluid rounded" alt="...">
      <figcaption class="figure-caption"></figcaption>
    </figure>
  </div>

  <div class="nav justify-content-center">
    <%=link_to 'Realizar pedido', new_request_path, class:"btn btn-light"%>
  </div>

app/views/home_pages/new.html.erb
<h1>New Home Page</h1>

<%= render 'form', home_page: @home_page %>

<%= link_to 'Back', home_pages_path %>

app/views/home_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apresentacao:</strong>
  <%= @home_page.apresentacao %>
</p>

<%= link_to 'Edit', edit_home_page_path(@home_page) %> |
<%= link_to 'Back', home_pages_path %>